version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    entrypoint: ./docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    tty: true
  migration:
    image: postgres
    command: "python manage.py migrate"
    volumes:
      - .:/code
    depends_on:
      - db