FROM python:3.8
WORKDIR /code
ADD . /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/
ADD /code/django_rest_imageupload_backend\django_rest_imageupload_backend/settings.py  /code/django_rest_imageupload_backend\django_rest_imageupload_backend/settingsx.py  
ADD /code/django_rest_imageupload_backend\django_rest_imageupload_backend/settings2.py  /code/django_rest_imageupload_backend\django_rest_imageupload_backend/settings.py  
